# fly.toml app configuration file
app = "corardei" # <-- Cambia "coradei" por el nombre exacto de tu app en Fly.io (si le pusiste otro)

primary_region = "gru" # Sao Paulo, la región más cercana disponible (EZE fue desactivada por Fly)

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
